const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.wrap,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.TextBox,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Eponesh_GameScore.Acts.FullscreenOpen,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.ScriptsInEvents.Invate_Event1_Act1,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.GamePush_Channels.Acts.FetchFeedMessages,
		C3.Plugins.GamePush_Channels.Cnds.OnFeedMessagesFetch,
		C3.Plugins.GamePush_Channels.Cnds.EachMessage,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.GamePush_Channels.Exps.CurMessageText,
		C3.Plugins.GamePush_Channels.Acts.DeleteMessage,
		C3.Plugins.GamePush_Channels.Exps.CurMessageID,
		C3.Plugins.GamePush_Channels.Acts.SendFeedMessage,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{BtnLead: 0},
	{BtnPlay: 0},
	{Тач: 0},
	{"8Направлений": 0},
	{СледитьЗа: 0},
	{Cat: 0},
	{Якорь: 0},
	{NubBG: 0},
	{DragDrop: 0},
	{Nub: 0},
	{Заворачивание: 0},
	{Спрайт: 0},
	{GamePush: 0},
	{Синусоида: 0},
	{Спрайт3: 0},
	{Спрайт2: 0},
	{Спрайт4: 0},
	{ТайловыйФон: 0},
	{Твёрдый: 0},
	{solid: 0},
	{num: 0},
	{score: 0},
	{SpriteFont_Importer: 0},
	{Спрайт5: 0},
	{solid2: 0},
	{Аудио: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{ВводТекста: 0},
	{Browser: 0},
	{Button: 0},
	{GamePushChannels: 0},
	{Спрайт9: 0},
	{ОбУстройстве: 0},
	{Sine: 0},
	{Buttons: 0},
	{invate: 0},
	{IsMoving: 0},
	{height: 0},
	{weight: 0},
	{Refid: 0},
	{Botname: 0},
	{Selfid: 0},
	{MessageCount: 0}
];

self.InstanceType = {
	BtnLead: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Cat: class extends self.ISpriteInstance {},
	NubBG: class extends self.ISpriteInstance {},
	Nub: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	solid: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteFontInstance {},
	SpriteFont_Importer: class extends self.IArrayInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	solid2: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Browser: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	GamePushChannels: class extends C3.Plugins.GamePush_Channels.Instance {},
	Спрайт9: class extends self.ISpriteInstance {},
	ОбУстройстве: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {}
}